image: ralfjung/opam-ci:opam2

stages:
  - build

variables:
  CPU_CORES: "10"
  OCAML: "ocaml-variants.5.1.1+options ocaml-option-flambda"

.template: &template
  stage: build
  tags:
  - fp
  script:
  - git clone https://gitlab.mpi-sws.org/iris/ci.git ci -b opam2
  - ci/buildjob
  cache:
    key: "$CI_JOB_NAME"
    paths:
    - _opam/
  only:
  - /^master/@iris/lambda-rust
  - /^ci/@iris/lambda-rust
  except:
  - triggers
  - schedules
  - api

## Build jobs

build-coq.8.20.1:
  <<: *template
  variables:
    OPAM_PINS: "coq version 8.20.1"
    DENY_WARNINGS: "1"
    MANGLE_NAMES: "1"
    # Mostly to make the lifetime logic available
    OPAM_PKG: "1"

trigger-iris.timing:
  <<: *template
  variables:
    OPAM_PINS: "coq version 8.20.1   git+https://gitlab.mpi-sws.org/$IRIS_REPO#$IRIS_REV"
  tags:
  - fp-timing
  only:
  - triggers
  - schedules
  - api
